### ISSUE TITLE
Feedback: Too much boilerplate

### ISSUE THREAD

**Issue by Steffen-Wolf** [dlmbl/07_failure_modes#6]
I have noticed that implementing the dense network and the integrated gradients takes a long time (for most students) and does not add to appeal of this exercise. I think we should just give the solution for both tasks and instead come up with a data question that people should investigate. That would create more engagement with the actual course material.

**Comment by cmalinmayor** [comment]
Done - There is now no code in the exercise! Thanks for the feedback :)
