### ISSUE TITLE
Improvement suggestions from 2023

### ISSUE THREAD

**Issue by cmalinmayor** [dlmbl/07_failure_modes#8]
- [x] Part 2 was too easy - they knew what would happen from lecture, and understood that it would short cut and perform better on tainted data and worse on test data. Could cut this discussion out.
- [x] Part 5 - add a task to train on both datasets and then try applying to both. This is very easy with ConcatDatasets and works very well. Could add a thought question about what happens if we train sequentially (MNIST and then Fashion) instead of both shuffled together.
- [ ] Would be interesting to only corrupt 25%/50%/75% of the 4s/7s, and/or add the same corruption to other digits in the test set, to have a more interesting and/or realistic experiment.
- [x] More coordination with Knowledge Extraction lecture - maybe put failure modes after so we can leverage the info from the lecture. The very surface level explanation of Integrated Gradients with a note that we will learn more tomorrow was not satisfying for everyone.
- [ ] Add model class predictions to integrated gradients section. Possibly a function to visualize random examples from specific classes (different 4s, 7s, other digits).
- [ ] We mentioned bad data handling as a common "failure mode" in lecture. Teaching them how to find and debug these kinds of issues would be very very useful (but also frustrating if we don't scaffold properly). Some examples: Loading mismatched images and labels (e.g. due to bad naming conventions of files), augmenting or not augmeting your masks inappropriately, messing up your train test split. Could provide visualization function to aid detection of the issue.

**Comment by afoix** [comment]
We will try to integrate all the feedback from this issue for 2024

**Comment by cmalinmayor** [comment]
Don't worry about integrating ALL of it! I was writing all my thoughts down so I didn't forget, but some of them are definitely bonus thoughts :) so interpret as you see fit!

**Comment by afoix** [comment]
Hello :-) I've implemented The second suggestion and also with @adjavon we are doing the four suggestion. I'll speed up part 2 as suggested as well although I thing is interesting for the narrative overall. Thank you @cmalinmayor
